---
title: "STOP2_Sets"
author: "Jordan Lo"
date: "2024-01-08"
output: html_document
---

```{r}
# tidyverse allows us to do our data processing
library(tidyverse)
# readxl allows us to read excel files
library(readxl)
# writexl allows us to write to excel files
library(writexl)
# qpcR lets us merge data frames side by side
library(qpcR)
```

```{r}
raw <- read_excel("B:/CF.CRA.STOP2.Study/Sample manifests/complete manifest.xlsx")

raw <- raw [1:14] %>%
  unite("Study_ID",
        `Participant Study ID`:`Visit ID`,
        sep = "-") 

raw <- raw[, c("Study_ID",
               "Barcode",
               "Freezer Section",
               "Shelf",
               "Rack",
               "Box",
               "Position",
               "Obs_volume",
               "id_study_visit")]

unique_id  <- raw %>%
  distinct(Study_ID)

groups <- split(unique_id,
                rep(1:29, 
                    c(76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76)))
set_1 <- as.data.frame(groups[1])

set_1_plate <- raw %>%
    filter(Study_ID %in% set_1$Study_ID)

set_generation <- function(index) {
  set <- as.data.frame(groups[index])
  set_plate <- raw %>%
    filter(Study_ID %in% set$Study_ID) %>%
     separate(Study_ID,
              into = c("Sample",
                       "Study",
                       "Visit"),
              sep = "-") %>%
     unite("Sample",
           c("Sample", "Study"),
           sep = "-")
  set_plate <- set_plate %>%
    relocate(id_study_visit,
             .after = Visit)
  # print(set)
}

sets <- 1:29

all_sets <- lapply(sets, set_generation)

names(all_sets) <- c("Set 1",
                     "Set 2",
                     "Set 3",
                     "Set 4",
                     "Set 5",
                     "Set 6",
                     "Set 7",
                     "Set 8",
                     "Set 9",
                     "Set 10",
                     "Set 11",
                     "Set 12",
                     "Set 13",
                     "Set 14",
                     "Set 15",
                     "Set 16",
                     "Set 17",
                     "Set 18",
                     "Set 19",
                     "Set 20",
                     "Set 21",
                     "Set 22",
                     "Set 23",
                     "Set 24",
                     "Set 25",
                     "Set 26",
                     "Set 27",
                     "Set 28",
                     "Set 29")

# writes multiple excel files using the list of data frames above
write_xlsx(all_sets,
           path = "B:/CF.CRA.STOP2.Study/Subaliquot/pull_list_by_set_v2.xlsx")
```

